name: dog_food
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.5.4


dependencies:
  flutter:
    sdk: flutter
  carousel_slider: ^4.2.1
  url_launcher: ^6.3.1
  auto_size_text: ^3.0.0
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  mpesa_flutter_plugin: 
  http: ^0.13.6 


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/assets/images/  
  fonts:
    - family: NotoSans
      fonts:
        - asset: assets/fonts/Noto_Sans/NotoSans-Regular.ttf
        - asset: assets/fonts/Noto_Sans/NotoSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/Noto_Sans/NotoSans-Italic.ttf
          style: italic
